/**
 * tslib-ios-ffi — C bindings for the tslib TeamSpeak 3/6 client library.
 *
 * Threading model:
 *   - tslib_client_connect() spawns a dedicated worker thread that owns the
 *     underlying Client and its Tokio runtime.
 *   - tslib_client_poll_event() returns JSON events (free with tslib_string_free).
 *   - All other client functions marshal a command to the worker thread and
 *     block until it completes.
 *
 * Memory management:
 *   - Returned strings must be freed with tslib_string_free().
 *   - Handles must be freed with the matching tslib_*_free() / tslib_*_destroy().
 */


#ifndef TSLIB_IOS_H
#define TSLIB_IOS_H

#pragma once

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by the C API.
 */
typedef enum TsLibError {
  OK = 0,
  INVALID_ARGUMENT = 1,
  CONNECTION_FAILED = 2,
  NOT_CONNECTED = 3,
  TIMEOUT = 4,
  PERMISSION_DENIED = 5,
  CHANNEL_ERROR = 6,
  IDENTITY_ERROR = 7,
  INTERNAL_ERROR = 99,
} TsLibError;

/**
 * Opaque handle to a TeamSpeak identity.
 */
typedef struct TsLibIdentity {
  uint8_t _private[0];
} TsLibIdentity;

/**
 * Opaque handle to a TeamSpeak client connection.
 */
typedef struct TsClient {
  uint8_t _private[0];
} TsClient;

/**
 * Opaque handle to an Opus encoder/decoder pair.
 */
typedef struct TsOpus {
  uint8_t _private[0];
} TsOpus;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new identity.
 *
 * # Safety
 * Returns a pointer that must be freed with `tslib_identity_free`.
 */
struct TsLibIdentity *tslib_identity_create(void);

/**
 * Load an identity from a file.
 *
 * # Safety
 * - `path` must be a valid null-terminated UTF-8 string.
 * - Returns a pointer that must be freed with `tslib_identity_free`.
 */
struct TsLibIdentity *tslib_identity_load(const char *path);

/**
 * Import an identity from its exported string form.
 *
 * # Safety
 * - `data` must be a valid null-terminated UTF-8 string.
 * - Returns a pointer that must be freed with `tslib_identity_free`.
 */
struct TsLibIdentity *tslib_identity_import_string(const char *data);

/**
 * Export an identity to its string form.
 *
 * # Safety
 * - `identity` must be a valid pointer from `tslib_identity_create` or load.
 * - Returns a string that must be freed with `tslib_string_free`.
 */
char *tslib_identity_export_string(const struct TsLibIdentity *identity);

/**
 * Save an identity to a file.
 *
 * # Safety
 * - `identity` must be a valid pointer from `tslib_identity_create` or load.
 * - `path` must be a valid null-terminated UTF-8 string.
 */
enum TsLibError tslib_identity_save(const struct TsLibIdentity *identity, const char *path);

/**
 * Get the unique ID of an identity.
 *
 * # Safety
 * - `identity` must be a valid pointer.
 * - Returns a string that must be freed with `tslib_string_free`.
 */
char *tslib_identity_unique_id(const struct TsLibIdentity *identity);

/**
 * Get the security level of an identity.
 */
int tslib_identity_security_level(const struct TsLibIdentity *identity);

/**
 * Free an identity.
 *
 * # Safety
 * `identity` must be a valid pointer from `tslib_identity_create` or load.
 */
void tslib_identity_free(struct TsLibIdentity *identity);

/**
 * Connect to a TeamSpeak server.
 *
 * # Safety
 * - All string parameters must be valid null-terminated UTF-8 strings or NULL.
 * - `identity` must be a valid pointer (ownership is NOT transferred).
 * - Returns a pointer that must be freed with `tslib_client_free`.
 */
struct TsClient *tslib_client_connect(const char *address,
                                      const struct TsLibIdentity *identity,
                                      const char *nickname,
                                      const char *server_password,
                                      const char *channel,
                                      const char *channel_password);

/**
 * Send an encoded audio frame to the server.
 *
 * # Safety
 * `data` must point to `len` valid bytes.
 */
enum TsLibError tslib_client_send_audio(struct TsClient *client,
                                        const unsigned char *data,
                                        uintptr_t len,
                                        int codec);

/**
 * Notify the server whether our microphone is muted.
 */
enum TsLibError tslib_client_set_input_muted(struct TsClient *client, int muted);

/**
 * Move to a channel (optionally password protected).
 *
 * # Safety
 * `password` must be a valid null-terminated UTF-8 string or NULL.
 */
enum TsLibError tslib_client_move_to_channel(struct TsClient *client,
                                             uint64_t channel_id,
                                             const char *password);

/**
 * Send a message to the whole server.
 *
 * # Safety
 * `message` must be a valid null-terminated UTF-8 string.
 */
enum TsLibError tslib_client_send_server_message(struct TsClient *client, const char *message);

/**
 * Send a message to the current channel.
 *
 * # Safety
 * `message` must be a valid null-terminated UTF-8 string.
 */
enum TsLibError tslib_client_send_channel_message(struct TsClient *client, const char *message);

/**
 * Send a private message to a user.
 *
 * # Safety
 * `message` must be a valid null-terminated UTF-8 string.
 */
enum TsLibError tslib_client_send_private_message(struct TsClient *client,
                                                  uint16_t target,
                                                  const char *message);

/**
 * Disconnect from the server (the handle stays valid until `tslib_client_free`).
 */
enum TsLibError tslib_client_disconnect(struct TsClient *client);

/**
 * Get the current connection state (0..4).
 */
int tslib_client_state(const struct TsClient *client);

/**
 * Pop the next event (JSON string) from the event queue.
 *
 * Returns NULL when the queue is empty. The returned string must be freed
 * with `tslib_string_free`.
 */
char *tslib_client_poll_event(const struct TsClient *client);

/**
 * Get a full JSON snapshot of the current server state (channels, users, ...).
 *
 * The returned string must be freed with `tslib_string_free`.
 */
char *tslib_client_snapshot(const struct TsClient *client);

/**
 * Disconnect and free the client handle (joins the worker thread).
 *
 * # Safety
 * `client` must be a valid pointer from `tslib_client_connect`.
 */
void tslib_client_free(struct TsClient *client);

/**
 * Free a string returned by this library.
 *
 * # Safety
 * `s` must be a pointer returned by a `tslib_*` string function.
 */
void tslib_string_free(char *s);

/**
 * Create an Opus encoder/decoder pair.
 *
 * Returns NULL on failure. Free with `tslib_opus_destroy`.
 */
struct TsOpus *tslib_opus_create(int sample_rate, int channels, int bitrate, int frame_size_ms);

/**
 * Encode one frame of 16-bit PCM samples into Opus.
 *
 * # Safety
 * - `pcm` must point to `pcm_len` valid i16 samples (at least one frame).
 * - `out` must point to `out_cap` valid bytes.
 * Returns the number of bytes written, or a negative error code.
 */
int tslib_opus_encode(struct TsOpus *codec,
                      const int16_t *pcm,
                      uintptr_t pcm_len,
                      uint8_t *out,
                      uintptr_t out_cap);

/**
 * Decode one Opus packet into 16-bit PCM samples.
 *
 * # Safety
 * - `data` must point to `len` valid bytes.
 * - `out` must point to `out_cap` valid i16 samples.
 * Returns the number of samples written, or a negative error code.
 */
int tslib_opus_decode(struct TsOpus *codec,
                      const uint8_t *data,
                      uintptr_t len,
                      int16_t *out,
                      uintptr_t out_cap);

/**
 * Free an Opus codec pair.
 *
 * # Safety
 * `codec` must be a valid pointer from `tslib_opus_create`.
 */
void tslib_opus_destroy(struct TsOpus *codec);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* TSLIB_IOS_H */
