/**
 * ts3-rust — C FFI wrapper around ReSpeak/tsclientlib.
 *
 * Threading: connect() spawns a background worker that owns the Tokio runtime
 * and all tsclientlib connections. All exported functions marshal commands to
 * the worker; connect blocks until the connection is established (or fails).
 *
 * Logging: call init_logger() once, then ts3_set_log_callback() to receive
 * Rust log lines as C strings.
 */


#ifndef TS3_RUST_H
#define TS3_RUST_H

#pragma once

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Receives decoded audio frames: (connection_id, user_id, codec, data, len).
 * `data` is only valid for the duration of the call.
 */
typedef void (*Ts3AudioCallback)(uint64_t, uint16_t, uint8_t, const uint8_t*, uintptr_t);

/**
 * Receives talk status changes: (connection_id, user_id, talking).
 */
typedef void (*Ts3TalkCallback)(uint64_t, uint16_t, int);

/**
 * Opaque handle to an Opus encoder/decoder pair.
 */
typedef struct Ts3Opus {
  uint8_t _private[0];
} Ts3Opus;

typedef void (*LogCallback)(const char*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the Rust logging system. Safe to call multiple times.
 */
void init_logger(void);

/**
 * Register a callback that receives every Rust log line as a C string.
 *
 * # Safety
 * `callback` must be a valid function pointer. It may be called from the
 * Rust worker thread; the Swift side must not touch the UI from it directly.
 */
void ts3_set_log_callback(void (*callback)(const char*));

/**
 * Register the callback that receives incoming voice frames.
 *
 * # Safety
 * The callback may be invoked from the Rust worker thread. `data`/`len` are
 * only valid during the call; copy them out before returning.
 */
void ts3_set_audio_callback(Ts3AudioCallback callback);

/**
 * Register the callback that receives talk status changes (1 = talking).
 *
 * # Safety
 * The callback may be invoked from the Rust worker thread.
 */
void ts3_set_talk_callback(Ts3TalkCallback callback);

/**
 * Connect to a TeamSpeak 3 server and return a connection id.
 *
 * Returns `0` on failure (invalid arguments, timeout, or server rejection).
 * Blocks until connected (up to ~15s).
 *
 * # Safety
 * All string parameters must be valid null-terminated UTF-8 strings; the
 * optional `password` may be NULL.
 */
uint64_t ts3_connect(const char *server, uint16_t port, const char *nickname, const char *password);

/**
 * Disconnect from the server and release the connection.
 */
void ts3_disconnect(uint64_t connection_id);

/**
 * Send a text message to the current channel.
 *
 * Returns `0` on success, `-1` on failure.
 *
 * # Safety
 * `message` must be a valid null-terminated UTF-8 string.
 */
int32_t ts3_send_message(uint64_t connection_id, const char *message);

/**
 * Send one encoded audio frame to the server (non-blocking, fire-and-forget).
 *
 * `codec` uses TeamSpeak protocol ids: 4 = Opus voice, 5 = Opus music.
 * Returns `0` on accepted, `-1` on invalid input or no worker.
 *
 * # Safety
 * `data` must point to `len` valid bytes.
 */
int32_t ts3_send_audio(uint64_t connection_id, const uint8_t *data, uintptr_t len, int codec);

/**
 * Create an Opus encoder/decoder pair. Free with `ts3_opus_destroy`.
 */
struct Ts3Opus *ts3_opus_create(int sample_rate, int channels, int bitrate, int frame_size_ms);

/**
 * Encode one frame of 16-bit PCM into Opus.
 *
 * Returns the number of bytes written, or a negative error code.
 *
 * # Safety
 * - `pcm` must point to `pcm_len` valid i16 samples (at least one frame).
 * - `out` must point to `out_cap` valid bytes.
 */
int ts3_opus_encode(struct Ts3Opus *codec,
                    const int16_t *pcm,
                    uintptr_t pcm_len,
                    uint8_t *out,
                    uintptr_t out_cap);

/**
 * Decode one Opus packet into 16-bit PCM samples.
 *
 * Returns the number of samples written, or a negative error code.
 *
 * # Safety
 * - `data` must point to `len` valid bytes.
 * - `out` must point to `out_cap` valid i16 samples.
 */
int ts3_opus_decode(struct Ts3Opus *codec,
                    const uint8_t *data,
                    uintptr_t len,
                    int16_t *out,
                    uintptr_t out_cap);

/**
 * Free an Opus codec pair.
 *
 * # Safety
 * `codec` must be a valid pointer from `ts3_opus_create`.
 */
void ts3_opus_destroy(struct Ts3Opus *codec);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* TS3_RUST_H */
